### PR TITLE
Add my name to contributors and minor formatting fix

### PR DESCRIPTION
**Pull request by meenbeese**
I preemptively added my name to the contributors list as I hope to contribute more on the Android front so I hope that's okay. I already have more commits than most of the contributors currently listed here. I also made some fixes for leading and trailing whitespaces in the README.

### CODE REVIEW

**Comment by KRTirtho** [comment]
Awesome to have you on board. Since you've taken oath to be the android dev I hope you'll contribute to that part
Also, do you know how to write Android Auto template UI?

**Comment by KRTirtho** [comment]
If you've time & knowledge addition of it will be huge contribution

**Comment by KRTirtho** [comment]
Make sure to be in the Discord server. There we can have talk about the development

**Comment by meenbeese** [comment]
> Awesome to have you on board.

Thanks for welcoming me. I appreciate all of your work on Spotube as it is a great client.

> Since you've taken oath to be the android dev I hope you'll contribute to that part.

I have some experience with Java/Kotlin but Dart is new to me so I will have to learn that better before I contribute.

> Also, do you know how to write Android Auto template UI?

I don't really know but I am sure that I can learn it easily.


Also, I joined the Discord server now. Thanks for reminding me.

**Comment by KRTirtho** [comment]
Love to have u here

**Comment by meenbeese** [comment]
> Ping me on the #development channel. So I'd  know who you're?

Done! Check your Discord.

**Pull request merged**
