### PR TITLE
add `gst-plugins-good` in PKGBUILD for arch linux

### PR DESCRIPTION
**Pull request by RomanJos**
I had this line  `GStreamer element autoaudiosink not found. Please install it` and couldn't start playing a song, after installing `gst-plugins-good` it worked.

I now have `WebKit wasn't able to find a WebVTT encoder. Subtitles handling will be degraded unless gst-plugins-bad is installed.` but installing it only get rid of the message without having any noticeable improvement so I didn't put it in the PKGBUILD since the plugin have a lot of dependencies.

### CODE REVIEW

**Comment by KRTirtho** [comment]
`gst-plugins-good` & `gst-plugins-bad` or only `gstreamer` are installed in Linux OS by default. Also `gst-plugins-good` are collection of  audio related plugins & some of them are not even directly related to Spotube at all. Your OS have had `gstreamer` installed, right? If not how you were even using your computer audio?

**Comment by RomanJos** [comment]
Hello, yes I had `gstreamer` installed but not `gst-plugins-good` for some reasons. I have `gst-plugins-base` thought.

`gst-plugins-good` is required by `webkit2gtk` optionally for media decoding so I guess its the reason why spotube require it to play media.

Uninstalling `webkit2gtk` give me this by the way

```
flutter: `just_audio_libwinmedia` threw an error: Invalid argument(s): Failed to load dynamic library '/usr/share/spotube-bin/lib/libwinmedia.so': libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory. The app may not function as expected until you remove this plugin from pubspec.yaml
```

**Comment by KRTirtho** [comment]
Then I guess adding `webkit2gtk` as dependency makes more sense as it'd install all the required deps for spotube. Can you try adding `webkit2gtk` as dependency instead of `gstreamer-plugins-good` to see if it works as `webkit2gtk` is a direct dependency for `libwinmedia` (libwinmedia is the audio player's audio engine for spotube)

**Comment by RomanJos** [comment]
I had `webkit2gtk` as a dependencies for something else before installing spotube so it wouldn't make a difference here since `gstreamer-plugins-good` is optional for `webkit2gtk`. Tell me if you need more info

**Comment by KRTirtho** [comment]
Yeah, so I found out both `webkit2gtk` & `gst-plugins-good` are required. So I've to add both as dependency

**Review by KRTirtho — CHANGES_REQUESTED** [review]
Add `webkit2gtk` in `depends`

**Review by KRTirtho — APPROVED** [review]

**Pull request merged**
