### PR TITLE
fix: add missing dependency in debian package

### PR DESCRIPTION
**Pull request by Razuuu**
* fixes https://github.com/KRTirtho/spotube/issues/703

### CODE REVIEW

**Comment by KRTirtho** [comment]
It is kind of weird that it works fine on Ubuntu without libmpv2 or it's installed alongside mpv

**Review by KRTirtho — APPROVED** [review]

**Comment by Razuuu** [comment]
I can't explain lol

**Comment by acesabe** [comment]
On fully updated Ubuntu 22.04.3 LTS:

> $ sudo dpkg -i ~/Downloads/Spotube-linux-x86_64.deb 
(Reading database ... 298928 files and directories currently installed.)
Preparing to unpack .../Spotube-linux-x86_64.deb ...
Unpacking spotube (3.1.2+24) over (3.1.1+23) ...
dpkg: dependency problems prevent configuration of spotube:
 spotube depends on libmpv2; however:
  Package libmpv2 is not installed.

Of course there is no libmpv2 on Ubuntu 22.04.3 only libmpv1

**Comment by KRTirtho** [comment]
@acesabe yes yes you're right

**Comment by KRTirtho** [comment]
@Razuuu can you add `- libmpv2 | libmpv1` please?

**Comment by Razuuu** [comment]
I'm at work, i will do it this evening.

**Comment by KRTirtho** [comment]
Thanks :+1:

**Comment by Razuuu** [comment]
Package can't be found via apt
`joshua@b450:~$ apt search libmpv1
Sortierung… Fertig
Volltextsuche… Fertig
joshua@b450:~$ apt search libmpv2
Sortierung… Fertig
Volltextsuche… Fertig
libmpv2/testing,now 0.36.0-1 amd64  [installiert]
  Videoplayer auf Basis von MPlayer/mplayer2 (Client-Bibliothek)
`

I will do a commit that adds libmpv1 for ubuntu-based systems

**Comment by KRTirtho** [comment]
@Razuuu you've to create a new PR for new changes

**Pull request merged**
