### PR TITLE
[Feature] Add Duration Match Algorithm (Needs Testing)

### PR DESCRIPTION
**Pull request by Demizo**
- Added duration matching option to track matching algorithms.

Matching based on song duration greatly improves Spotube's accuracy in playing the correct song. It also solves the issue of artists having more than one version of a song with the same name. Duration matching helps to root out music videos as well. While I personally believe that duration matching should be built into all the matching algorithms, I decided it might be best to just make it an option for now and see how it is received.

### CODE REVIEW

**Comment by KRTirtho** [comment]
>  duration matching should be built into all the matching algorithms

I think having it as a part of `authentic popular` would be a better choice. From my testing, I've found just matching the duration isn't good enough, as sometimes covers & remixes (even lofis) get ranked higher in result (maybe because official music videos contain off music stuff too sometimes). Though popular tracks work fine mostly but when we hit the local music, it fails almost all the time 😕

**Comment by Demizo** [comment]
I can look into this tomorrow. I agree with you, it is better suited as an "authenticity" tool than an algorithm on its own

**Comment by KRTirtho** [comment]
Let's keep it for the later release. The upcoming v2.4.0 already has a bunch of features and improvements :sweat_smile:. Also duration matcher needs some testing too which can take some time

**Comment by Demizo** [comment]
Duration matching is now integrated into both the popular and authentic matching algorithms. Songs within 10 seconds of the actual song duration are granted +1 rating. This should prevent duration matching from overpowering other methods of authentication while boosting the most authentic tracks. 10 seconds is a magic number and could be fine tuned with testing (especially needs testing with more niche music)

**Review by its0x08 — APPROVED** [review]

**Comment by KRTirtho** [comment]
Hey, @Demizo  can you sync with the latest changes?

**Comment by Demizo** [comment]
Sure!

**Pull request merged**
