### PR TITLE
Improve install.sh

### PR DESCRIPTION
**Pull request by RaptaG**
I still want to install the deps, so draft for now

### CODE REVIEW

**Comment by KRTirtho** [comment]
@RaptaG not done?

**Comment by RaptaG** [comment]
@KRTirtho no sorry I have exams

**Comment by KRTirtho** [comment]
Same bro. Looks like we're dying together :rofl:

**Comment by RaptaG** [comment]
@KRTirtho can I merge it? It is done!

**Comment by RaptaG** [comment]
I merged it dev, you can always return and make changes

**Pull request merged**
