### PR TITLE
[Feature] Organize Settings With Headers

### PR DESCRIPTION
**Pull request by Demizo**
Settings are now organized into headers.
The settings were cluttered and were not in an intuitive order. Now the settings are organized and the login has been moved to the top to aid first time users. The donation option has also been moved to the top for visibility (this could be moved to the "About" section at the cost of less visibility)

### CODE REVIEW

**Comment by KRTirtho** [comment]
Can you sync your fork with current changes ?

**Comment by Demizo** [comment]
Sure!

**Comment by KRTirtho** [comment]
> The donation option has also been moved to the top for visibility (this could be moved to the "About" section at the cost of less visibility)

I think this would be better. It kinda looks out of order when placed in the top :sweat_smile:

**Comment by Demizo** [comment]
Sounds good, I just didn't want to hide your support button ;P

**Comment by KRTirtho** [comment]
Thanks again for contribution :heart:

**Pull request merged**
