### PR TITLE
feat: LAN connect a.k.a control remote Spotube playback 

### LINKED ISSUE #1344: Spotify Connect
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Hi, so I love the Spotube App and I have been using it for quite a while now. I love the app, but the only thing that kept me from completely ditching Spotify was Spotify Connect. Basically, I could be playing music on my ;aptop, but I can control playback from my phone, as if it were a remote, and that is so useful.

### Suggested solution

 I was wondering, if it was possible to somehow integrate Spotify Connect into Spotube?

### Useful resources

_No response_

### Additional information

_No response_

### Self grab

- [ ] I'm ready to work on this issue!

### PR DESCRIPTION
**Pull request by KRTirtho**
Closes #1344 

* Adds remote control for Spotube running in same network (cross-platform)
* Adds bluetooth/other local output device selection

### CODE REVIEW

**Comment by Smarthome-Creator** [comment]
@KRTirtho, I have a question about this feature. How should it work?
I have the current version 3.6.0 on Windows, Mac and Android and had thought that I would be able to stream my music to my HiFi Berry or my Sonos sound system from there or control my Mac or Windows PC from my Android. Or have I misunderstood?

"Only" locally connected Bluetooth could be selected among the devices when I connect it to my JBL speaker.

**Comment by KRTirtho** [comment]
Make sure both devices are on the same wifi/network (LAN).

**Comment by Smarthome-Creator** [comment]
Well, if you're blind, you can't see the wood for the trees. ;-)
Thanks for the quick reply, great app, keep up the good work.

**Comment by KRTirtho** [comment]
Keep on vibing 🎶

**Pull request merged**
