### PR TITLE
Function for interactive login in the browser [BETA]

### PR DESCRIPTION
**Pull request by SantiiRepair**
https://github.com/KRTirtho/spotube/assets/94815926/67130b47-d097-451d-9aa7-be04c56d4556

### CODE REVIEW

**Comment by Peperehobbits01** [comment]
I mean, this is much easier to connect to a account that way... and I mean, a lot of programs are doing this thing. Tho, it may cause issues whit flatpaks... but I mean, I have looked at it, and well that's pretty good :)

**Comment by SantiiRepair** [comment]
> I mean, this is much easier to connect to a account that way... and I mean, a lot of programs are doing this thing. Tho, it may cause issues whit flatpaks... but I mean, I have looked at it, and well that's pretty good :)

It would be interesting for windows as it goes to the general public who do not know or find it complicated to activate using cookies.

**Comment by Peperehobbits01** [comment]
> > I mean, this is much easier to connect to a account that way... and I mean, a lot of programs are doing this thing. Tho, it may cause issues whit flatpaks... but I mean, I have looked at it, and well that's pretty good :)
> 
> It would be interesting for windows as it goes to the general public who do not know or find it complicated to activate using cookies.

I mean, there is (not a lot) but non advanced user on Linux to, and I mean, it's not because you know how tu use a terminal in Linux that you know how to use the dev tools of your web browser but yeah, it's good for the average user. And it's kind of a thing on the Android version already.

**Comment by KRTirtho** [comment]
This is a near perfect solution but the issue is with downloading a standalone chrome binary just to login. While 100MBs is not a lot nowadays but the user still has to download it and then they can login.
Only if there was a way to use the default browser to do this. I already tried with desktop_webview_window but that doesn't give us access to cookies which is what we need in order to authenticate.
Puppeteer luckily gives us that option but it still has to download the chrome/chromium binary

**Comment by SantiiRepair** [comment]
> This is a near perfect solution but the issue is with downloading a standalone chrome binary just to login. While 100MBs is not a lot nowadays but the user still has to download it and then they can login. Only if there was a way to use the default browser to do this. I already tried with desktop_webview_window but that doesn't give us access to cookies which is what we need in order to authenticate. Puppeteer luckily gives us that option but it still has to download the chrome/chromium binary

let me make a few corrections and I'll fix it.

**Comment by KRTirtho** [comment]
I think we can for now, use smaller builds of chromium that will give us minimal chrome that still has devtools protocol that puppeteer requires, removing other features that are not needed for us.

I know [mini_chromium](https://github.com/chromium/mini_chromium) project exists but I never saw any functional builds from it and not sure if it includes devtools supports.

Btw, for Windows 10 (>=21H1) and 11, Microsoft added Chromium based Edge. So, we can just use that by default in Windows. Otherwise we can fallback to downloading Chromium or just ask the user to give us the path to Chrome/chrome based browser if it's already installed. We can do the same for MacOS and Linux as well.

**Comment by KRTirtho** [comment]
Or, we could add `CookieManager` support to `desktop_webview_window`. Looking at their codebase, they're using [`ICoreWebView2`](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2) for Windows, [`WKWebView`](https://developer.apple.com/documentation/webkit) for MacOS and [`WebkitGTK`](https://webkitgtk.org/) for Linux

All of these has Cookie management support through different APIs
- [WebView2.CookieManager](https://webkitgtk.org/reference/webkit2gtk/stable/class.CookieManager.html) for `WebkitGtk` (linux)
- [ICoreWebView2CookieManager](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2cookiemanager?view=webview2-1.0.2478.35) for `ICoreWebView2` (windows)
- [HTTPCookieStorage](https://developer.apple.com/documentation/foundation/httpcookiestorage) for `WKWebView` (macos)

It is possible to write and platform independent implementation covering all this for each specific platforms. The library already uses Method Channels to accomplish all the functionalities.

**Comment by KRTirtho** [comment]
They already have Feature request open https://github.com/MixinNetwork/flutter-plugins/issues/125

**Comment by KRTirtho** [comment]
Finally! :partying_face: GetCookie support for Desktop platforms in `desktop_webview_window` :rocket: 
Now it's only matter of time, we implement it in Spotube. @SantiiRepair do you want to implement this same thing but using `desktop_webview_window`? You can open a separate PR with changes. Thanks for your ideas, it helped me a lot.

Pull Request: https://github.com/MixinNetwork/flutter-plugins/pull/349

**Comment by SantiiRepair** [comment]
> Finally! 🥳 GetCookie support for Desktop platforms in `desktop_webview_window` 🚀 Now it's only matter of time, we implement it in Spotube. @SantiiRepair do you want to implement this same thing but using `desktop_webview_window`? You can open a separate PR with changes. Thanks for your ideas, it helped me a lot.
> 
> Pull Request: [MixinNetwork/flutter-plugins#349](https://github.com/MixinNetwork/flutter-plugins/pull/349)

I will do it

**Comment by KRTirtho** [comment]
@SantiiRepair sorry I couldn't hold my enthusiasm so I kind of did it myself 😅 . It's in the `feat/desktop-webview` branch btw. Thanks for your all help ❤️ 

I will also release a nightly so everyone can check it out.

**Comment by KRTirtho** [comment]
I'm going to close this issue in favor of #1688 thanks to you :heart: 
Keep on vibing on Spotube!

**Pull request closed without merging**
