### PR TITLE
#961 / The music plays again after a pause - Resolved

### PR DESCRIPTION
**Pull request by talha828**
This video shows how the application behaved before and after fixing the bug.  Task (#926 & #961) Resolved

https://github.com/KRTirtho/spotube/assets/61588132/6d54571c-074e-43d8-a602-adf78cde0e25

### CODE REVIEW

**Comment by KRTirtho** [comment]
Unfortunately, this is not working and brings back old issue 15d466a04538ec70c3a0c132f2baaaf8690f8d4e. The issue of #961 and #926 happens when the audio-player was paused manually, not on Audio Interruption of other apps. But the events have 2 lifecycles: _BEGIN_ and _END_ where _BEGIN_ is supposed to start the action and _END_is supposed to clean up all the in between work. 
So, an audio interruption event that tells to pause the audio at the beginning must resume the audio when the interruption is gone. But the BEGIN and END events are not fired serially, and END events doesn't even need the BEGIN events to fire. Both are independent.

Solution is probably, differentiating between who has paused the audio, or simply we can have a flag `wasPausedByBeginEvent` that will be `true` when BEGIN pause event has paused the audio otherwise `false`

**Comment by talha828** [comment]
[Audio doesn't resume after the interruption ends] I now realize the only issue with my current solution is that the audio fails to resume after the interruption ends. However, it effectively resolves issue #916 [The music plays again after a pause]. My focus is now on managing a stream while playing in line with the interruption cycle.

**Comment by KRTirtho** [comment]
We can probably do this:

```diff
  MobileAudioService(this.playlistNotifier) {
    AudioSession.instance.then((s) {
      session = s;
      session?.configure(const AudioSessionConfiguration.music());
   
      bool wasPausedByBeginEvent = false;

      s.interruptionEventStream.listen((event) async {
        if (event.begin) {
          switch (event.type) {
            case AudioInterruptionType.duck:
              await audioPlayer.setVolume(0.5);
              break;
            case AudioInterruptionType.pause:
-          case AudioInterruptionType.unknown:
+         case AudioInterruptionType.unknown: {
              await audioPlayer.pause();
+              wasPausedByBeginEvent = true;
              break;
+          }
          }
        } else {
          switch (event.type) {
            case AudioInterruptionType.duck:
              await audioPlayer.setVolume(1.0);
              break;
            case AudioInterruptionType.pause:
-            case AudioInterruptionType.unknown:
+           case AudioInterruptionType.unknown: {
-                await audioPlayer.resume();
+               if(wasPausedByBeginEvent){
+                 await audioPlayer.resume();
+                 wasPausedByBeginEvent = false;
+               }
                break;
             }
          }
        }
      });

      s.becomingNoisyEventStream.listen((_) {
        audioPlayer.pause();
      });
    });
    audioPlayer.playerStateStream.listen((state) async {
      playbackState.add(await _transformEvent());
    });

    audioPlayer.positionStream.listen((pos) async {
      playbackState.add(await _transformEvent());
    });
    audioPlayer.bufferedPositionStream.listen((pos) async {
      playbackState.add(await _transformEvent());
    });
  }
```

**Comment by Nord1cWarr1or** [comment]
Any news?

**Comment by KRTirtho** [comment]
I actually fixed the issue myself as this PR took more time. So, I'm closing it.
Thanks to @talha828 although it's not merge ❤️

**Pull request closed without merging**
