### PR TITLE
Added checks to the youtube rank results method

### PR DESCRIPTION
**Pull request by equationslayer12**
see https://github.com/KRTirtho/spotube/discussions/1186

### CODE REVIEW

**Comment by equationslayer12** [comment]
It appears this PR also includes the commit from my [other PR](https://github.com/KRTirtho/spotube/pull/1196).

**Comment by KRTirtho** [comment]
Thanks for the contribution
Can you please remove the unrelated commits or revert back the unrelated changes?

**Review by varshith257 — APPROVED** [review]
LGTM

**Comment by equationslayer12** [comment]
Bringing this up, should this PR be accepted?

**Comment by KRTirtho** [comment]
Not sure as I recently added [song.link](https://song.link) support, which pretty much always results with accurate results.
Also, I tested out your PR, it works good for popular music. But for country music, or regional tracks it kind of falls of just like the old implementation

**Pull request closed without merging**
