### PR TITLE
docs: install via homebrew on macOS

### LINKED ISSUE #120: Add Spotube to Homebrew
**Is your feature request related to a problem? Please describe.**
Installation of Spotube on a Mac currently only is available by downloading the dmg from Github. It would be great to be able to use a package-manager ([Homebrew](https://brew.sh/)) for this.

**Describe the solution you'd like**
Add Spotube to [Homebrew casks](https://docs.brew.sh/Adding-Software-to-Homebrew#casks)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by JounQin**
close #120

### CODE REVIEW

**Review by dubeyanant — APPROVED** [review]

**Review by varshith257 — CHANGES_REQUESTED** [review]
Commit is missing related files. Use brew to install `brew install homebrew-x/x/spotube`, but code files are needed.

**Comment by JounQin** [comment]
@varshith257 I don't quite understand what code file should be changed?

**Comment by varshith257** [comment]
Need to add Spotube to Homebrew casks to support brew package-manager

**Comment by varshith257** [comment]
Need to add Spotube to Homebrew casks to support brew package-manager

**Comment by JounQin** [comment]
@varshith257 I still have no idea what's your meaning. The homebrew cask definition is maintained at https://github.com/homebrew-x/homebrew-x/blob/master/Casks/spotube.rb

**Comment by varshith257** [comment]
What I mean is that it needs to get it signed it to work as intended. So,it should be resolved before updating of documentation.

**Comment by JounQin** [comment]
It doesn't need to be signed to be functional (if not signed, the user must open the App by bypassing security check in settings), but it must be signed if we want it to be added into https://github.com/Homebrew/homebrew-cask project.

The why I'm maintaining the cask in my own tap.

**Comment by varshith257** [comment]
> It doesn't need to be signed to be functional (if not signed, the user must open the App by bypassing security check in settings), but it must be signed if we want it to be added into https://github.com/Homebrew/homebrew-cask project.
> 
> The why I'm maintaining the cask in my own tap.
> 
> It's great if the signing issue can be resolved, but it's likely difficult because the owner does not have a Mac.

IMO It's good practice to have it in Homebrew/homebrew-cask project. I think soo this issue lasted till now and waiting for signature issue to be resolved.

**Comment by JounQin** [comment]
The problem now is that signing is blocked. And we've already provided `.dmg` asset for Mac users. Whether included into https://github.com/Homebrew/homebrew-cask doesn't change anything right now.

**Comment by KRTirtho** [comment]
Thanks for the generous work ❤️ but we're closing this PR as we've already added Homebrew support through custom `tap`

**Pull request closed without merging**
