### PR TITLE
Update youtube_explode_dart dependency version (fixes endless loading issue)

### PR DESCRIPTION
**Pull request by sunryze-git**
Latest version of the dependency fixes endless loading bug due to update on server side end.

#1920 
#1922 
#1916 

I haven't tested it compiling straight from source. I tested it on the AUR package, editing pubspec and then building and installing with makepkg.

### CODE REVIEW

**Review by JacKna06 — APPROVED** [review]

**Comment by s-b-repo** [comment]
please approve this

**Comment by DerekGooding** [comment]
Why is this taking so long? The app is bricked! Days of complete outage with no support from the team? 

Unreliable. Set up dependabot already.

**Comment by Renegade-Master** [comment]
Temporary fix here. Android not working yet, but working on that today. Hopefully will get all platforms working until @KRTirtho can release an official update.
https://github.com/Renegade-Master/spotube/releases

**Review by Vitalii-code — APPROVED** [review]

**Review by notwithering — APPROVED** [review]

**Review by xkcd00 — APPROVED** [review]

**Review by ferreira710 — APPROVED** [review]

**Review by TruFelix — APPROVED** [review]

**Review by HowDoIprintHelloWorld — APPROVED** [review]

**Review by MiEc09 — APPROVED** [review]

**Review by GiorgeLucas — APPROVED** [review]

**Comment by KRTirtho** [comment]
Extremely sorry everyone for the delay. My father was in hospital and yesterday he had a CABG bypass surgery so I couldn't help but stay by him.
Luckily the operation was successful and he's fine now and can talk as well (within first 3 hours). Please pray and hope for him so that he'll have a quick recovery

After 5 days of trauma and taunting experience, I finally go some free time to update the app. Hopefully everyone will get an update by tomorrow

**Comment by KRTirtho** [comment]
Thanks to @Renegade-Master and @sunryze-git for helping everyone out

**Review by KRTirtho — APPROVED** [review]

**Comment by Vitalii-code** [comment]
I'm sorry to hear that, I wish your dad a speedy recovery.

**Comment by sunryze-git** [comment]
> Extremely sorry everyone for the delay. My father was in hospital and yesterday he had a CABG bypass surgery so I couldn't help but stay by him.
> 
> Luckily the operation was successful and he's fine now and can talk as well (within first 3 hours). Please pray and hope for him so that he'll have a quick recovery
> 
> 
> 
> After 5 days of trauma and taunting experience, I finally got some free time to update the app. Hopefully everyone will get an update by tomorrow

No worries. Hope all is well and goes well.

**Comment by Renegade-Master** [comment]
@KRTirtho 
It was a pleasure to help. You keep this repo very easy to work in.
Glad I could take some heat off you while you were with your dad. I hope he recovers fully soon ❤️

**Pull request merged**
