### PR TITLE
Improve Discord RPC

### PR DESCRIPTION
**Pull request by nexpid**
Cleans up the Discord RPC and makes the timestamp/timer accurate to the currently playing track.

Some notes:
- this is the first time I've worked with flutter/dart, please feel free to critique and/or fix some of my code
- [discord has recently added activity types to Discord RPC](https://x.com/advaithj1/status/1816655583107510517), so it would be nice if you could add that to https://github.com/KRTirtho/frb_plugins/tree/main/packages/flutter_discord_rpc :)

https://github.com/user-attachments/assets/50a3ec5d-aed5-4343-820b-a0ac5ca867ba

Current RPC for comparison:
current spotube Discord RPC

### CODE REVIEW

**Review by xhyrom — APPROVED** [review]
LGTM

**Comment by KRTirtho** [comment]
It works great. Awesome work ❤️ 

But there are some unrelated changes that were submitted. Also there's a merge conflict Can you please fix these?

**Review by KRTirtho — CHANGES_REQUESTED** [review]
Please remove the unrelated changes. We only need the `discord_provider.dart`'s changes.

**Comment by nexpid** [comment]
> Please remove the unrelated changes. We only need the `discord_provider.dart`'s changes.

The current `win32` dependency is outdated and building on Windows machines does not work unless it's updated, that's why I updated all deps

**Comment by nexpid** [comment]
Please also review @xhyrom's https://github.com/KRTirtho/frb_plugins/pull/1 PR, so I can add its activity type feature to this PR

**Comment by KRTirtho** [comment]
You should add that in a separate PR. I'll merge this PR now as it is working and link it to appropriate issues

**Comment by KRTirtho** [comment]
Actually, that's a really small change, I can add it by myself. Thanks for your PR!

**Pull request merged**
