### PR TITLE
docs: Rewrite README

### PR DESCRIPTION
**Pull request by RaptaG**
:)

### CODE REVIEW

**Comment by KRTirtho** [comment]
@RaptaG please follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) guidelines to properly format your commit messages to allow Changelog generators to pick up important info from that

**Comment by RaptaG** [comment]
> @RaptaG please follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) guidelines to properly format your commit messages to allow Changelog generators to pick up important info from that

Alright, sorry!

**Comment by RaptaG** [comment]
I suggest you create a squash commit so that the bot can create a changelog from the PR title

**Comment by KRTirtho** [comment]
Yeah that's what I was going to do 😄

**Comment by KRTirtho** [comment]
Btw, please add that we need more contributors and translators?
Also keep the installation links

**Comment by RaptaG** [comment]
>  Also keep the installation links
I will, I'm just working on improving them!

**Comment by KRTirtho** [comment]
Good enough. I like it. Thanks for the contribution!!!

**Review by KRTirtho — APPROVED** [review]

**Comment by RaptaG** [comment]
@KRTirtho can I remove the install instructions from the wiki

**Pull request merged**
