### PR TITLE
Fix search input onChanged event

### PR DESCRIPTION
**Pull request by a3ro-dev**
i am a spotify user and using that has a feature where while im typing the song name the songs keep appearing and it wasn't a case with spottube, so i removed a line where it was searching when enter key was pressed, and rather it was re-searching on every letter written, just like spotify

### CODE REVIEW

**Comment by GStudiosX2** [comment]
There probably should be some delay between each key press a key press shall reset the delay so you don't hit the rate limit so fast (maybe not true though I haven't tested)

**Comment by a3ro-dev** [comment]
cool, but i think it won't hit any rate limit or anything and adding a delay will only make the whole thing useless as then it would become same as typing the full word out and then hitting enter, but what im seeking is searching while every key is pressed, without any latency

**Comment by GStudiosX2** [comment]
> cool, but i think it won't hit any rate limit or anything and adding a delay will only make the whole thing useless as then it would become same as typing the full word out and then hitting enter, but what im seeking is searching while every key is pressed, without any latency
> 

Yeah true I guess but don't know what the rate limits are because Spotify doesn't really say exactly it just says it's calculated maybe people might start hitting it for a bit and then it might resolve it self https://developer.spotify.com/documentation/web-api/concepts/rate-limits

**Comment by KRTirtho** [comment]
We've to debounce the user input. There's actually a hook named `useDebounce` in `lib/hooks/utils/use_debounce.dart`

**Comment by KRTirtho** [comment]
Also, it looks like there was merge conflict that wasn't properly resolved and caused all sorts of changes in unrelated files like pubspec.lock, desktop_login.dart and authentication_provider.dart.

Please fix those.

**Comment by a3ro-dev** [comment]
okay
fixing

**Comment by a3ro-dev** [comment]
resolved issues ✔️

**Comment by a3ro-dev** [comment]
ahh doing that in a few days

**Pull request closed without merging**
