### PR TITLE
Added Turkish translation

### PR DESCRIPTION
**Pull request by eren-ince**
Added Turkish translation by Eren İnce. (eren-ince@github)

### CODE REVIEW

**Comment by KRTirtho** [comment]
Someone has already added Turkish language support. I guess you're targetting the `master` branch and it hadn't been yet merged with `dev`

**Comment by KRTirtho** [comment]
You've to pull changes from upstream

**Comment by eren-ince** [comment]
I changed it to _dev_ @KRTirtho

**Comment by KRTirtho** [comment]
Closing this PR as someone already added the Turkish translations. 

But thanks for contribution :heart:

**Pull request closed without merging**
