### PR TITLE
refactor: use tcp server based track matcher

### PR DESCRIPTION
**Pull request by KRTirtho**
- fixes automatically skipping
  - #870 
- fixes stuck and stuttering track 
  - #580
  - #1382
  - #1376
  - #1348
  - #1341
  - #1201
- fixes weird behaviour when re-arranging queue track 
  - #1193
  - #1267
- fixes big track loading delay
  - #1304
- fixes the alternative track source error
  - #1289
- fixes queue track removing not working properly
  - #1092
- fixes controls don't work on last track completion
  - #924 
- fixes downloaded songs, sometimes plays using online source
  - #688

### CODE REVIEW

**Comment by KRTirtho** [comment]
@owencz1998 @MerkomassDev @karniv00l 
It'd be nice if you guys can test out the playback and check if it's meeting expectations

**Comment by MerkomassDev** [comment]
So far I managed to play multiple (3 but I could go further) playlists at once


When you want to switch playlists, you're only able to switch to a playlist you haven't played yet as switching doesn't "turn off the currently playing playlist status"


You can't even switch to an individual song from an already played playlist 

And for the playback, it performs about as expected so far, haven't got stuck on a song  yet

**Comment by MerkomassDev** [comment]
Testing it further and found out, that I can play all songs from the first played playlist and also songs that are shared with the first played playlist 

Playlists which I haven't played yet can be played but I can't switch to them back after playing another one

**Comment by MerkomassDev** [comment]
Whenever there's not a song playing, the current playing song thing is empty (it shouldn't display at all)

**Comment by KRTirtho** [comment]
Thanks @MerkomassDev for mentioning the issues. I faced the last one but forgot to add a fix 😅

**Comment by KRTirtho** [comment]
I fixed all the issue you faced.

**Pull request merged**
