### PR TITLE
Android: Filter Device To Force High Frame Rate

### PR DESCRIPTION
**Pull request by brianabdl**
In a device like mine (**Xiaomi**), applying force HFR is resulting in a drop fps.
Filtering the device brand using `AndroidDeviceInfo.brand` helps to fix this bug.

**Note: My current Display Frame Rate is set to 90Hz**

| Before | After |
| ------ | ------ |
|  |  |

### CODE REVIEW

**Comment by KRTirtho** [comment]
I'm not sure why but I also use a realme narzo 50. Which has 120hz refresh-rate and it's buttery smooth

**Comment by KRTirtho** [comment]
Maybe instead of filtering devices, we let the user choose if they want this or not?

**Comment by KRTirtho** [comment]
We can enable high refresh rate by default but we'll check if the current refresh rate is >=60 or not. If it's not we'll ask the user to disable it with a dialog in the settings with toggle

**Comment by Rewtio** [comment]
That's a good idea, although it's not every brand device that uses the buggy OS has this bug

**Comment by Rewtio** [comment]
Or maybe, you could detect the after-changes fps with the target set fps, 
if after changes, the current fps is lower than the target set fps, revert using the old fps

**Comment by KRTirtho** [comment]
Hmm, that's also true. Yeah lets go that direction

**Comment by brianabdl** [comment]
Hey, just wanna catch up, is there any improvement that I can make for this PR?

**Pull request merged**
