### PR TITLE
Add `network.server` to macos release entitlements

### LINKED ISSUE #17: Can't Login in MacOS
Also I can't login. My browser is unable to find localhost:4304. I tried all browsers and none of them worked.

_Originally posted by @highjeans in https://github.com/KRTirtho/spotube/issues/9#issuecomment-1027529246_

### PR DESCRIPTION
**Pull request by karniv00l**
Fixes #17 

Missing server permissions in release mode:

```bash
flutter: [Launching]: https://accounts.spotify.com/authorize?response_type=code&client_id=&redirect_uri=http%3A%2F%2Flocalhost%3A4304%2Fauth%2Fspotify%2Fcallback&code_challenge=&code_challenge_method=S256&scope=user-library-read+user-library-modify+user-read-private+user-read-email+user-follow-read+user-follow-modify+playlist-read-collaborative
flutter: [connectIpc]: SocketException: Failed to create server socket (OS Error: Operation not permitted, errno = 1), address = 127.0.0.1, port = 4304
flutter: #0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:988)
<asynchronous suspension>
#1      connectIpc (package:spotube/helpers/server_ipc.dart:11)
<asynchronous suspension>
#2      oauthLogin (package:spotube/helpers/oauth-login.dart:24)
<asynchronous suspension>

flutter: [oauthLogin()] SocketException: Failed to create server socket (OS Error: Operation not permitted, errno = 1), address = 127.0.0.1, port = 4304
flutter: #0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:988)
<asynchronous suspension>
#1      connectIpc (package:spotube/helpers/server_ipc.dart:11)
<asynchronous suspension>
#2      oauthLogin (package:spotube/helpers/oauth-login.dart:24)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SocketException: Failed to create server socket (OS Error: Operation not permitted, errno = 1), address = 127.0.0.1, port = 4304
#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:988)
<asynchronous suspension>
#1      connectIpc (package:spotube/helpers/server_ipc.dart:11)
<asynchronous suspension>
#2      oauthLogin (package:spotube/helpers/oauth-login.dart:24)
<asynchronous suspension>
```

### CODE REVIEW

**Comment by KRTirtho** [comment]
Does this make the OAuth login process work? I mean the IPC login part?

**Comment by karniv00l** [comment]
> Does this make the OAuth login process work? I mean the IPC login part?

Yes

**Comment by karniv00l** [comment]
Sorry that I didn't report that earlier. It works in debug mode because there are permissions in place for that mode by default. There is also a problem with the playback but I'll report that in a separate issue and try to debug in spare time.

**Comment by KRTirtho** [comment]
Thanks for the contribution❤️

**Comment by benyaminbeyzaie** [comment]
I can't run the app from releases please update release. Thanks.

**Pull request merged**
